### ISSUE TITLE
How to change default align to right 

### ISSUE THREAD

**Issue by milad777v2** [davidroyer/vue2-editor#239]
hello 
How to change default align to right ?

**Comment by papalardo** [comment]
Try this
```vue

<template>
    <vue-editor 
        id="editor" 
        ref="editor" 
    />
</template>

<script>

import { VueEditor } from "vue2-editor";

export default {
    components: {
        VueEditor
    },
    mounted() {
        // this.$refs.editor.quill.format('direction', 'rtl');
        this.$refs.editor.quill.format('align', 'right');
    },
}
</script>
```

Or
```css
.ql-editor {
  /* direction: rtl; */
  text-align: right !important;
}
```
