### ISSUE TITLE
Disable image function in toolbar

### ISSUE THREAD

**Issue by ndum** [davidroyer/vue2-editor#31]
Hi,

Is there an easyway to use the default toolbar but without the image function?

**Comment by masoomulhaqs** [comment]
This is hacky, but easy.

```css
  .ql-toolbar .ql-formats .ql-image {
    display: none;
  }
```
