### ISSUE TITLE
How disable copy/paste

### ISSUE THREAD

**Issue by zarlo12** [davidroyer/vue2-editor#408]
How disable copy/paste

**Comment by leobezr** [comment]
You could disable it using css 
```css
.ql-editor {
  user-select: none;
}
```
