### ISSUE TITLE
editor with element-ui component will display style error

### ISSUE THREAD

**Issue by jsasdw1991** [davidroyer/vue2-editor#68]
![image](https://user-images.githubusercontent.com/6205001/36011944-bcf367b0-0d95-11e8-9d54-95bd45613207.png)

```javascript
  <el-form-item label="文档内容：" prop="content">
    <el-input v-model="doc.content"></el-input>
    <el-row>
      <el-col :span="24">
        <vue-editor v-model="doc.content"></vue-editor>
      </el-col>
    </el-row>
  </el-form-item>
```

**Comment by jsasdw1991** [comment]
my solution:

```css
<style lang="scss">
.ql-picker-label {
  display: flex !important;
}
</style>

```

Is there a better way？
